name: Fork notification
on: [ fork ]

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04F73T9Z9T'
          slack-message: "Someone forked this repository!${{ github.repository.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
